version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-29
    environment:
      - TERM: dumb
      - JVM_OPTS: -Xmx1024m
      - _JAVA_OPTIONS: "-Xmx1024m"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "excuseme/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
            - ~/.m2
          key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "excuseme/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew :excuseme:test
      - store_artifacts:
          path: excuseme/build/reports
          destination: reports